### PR TITLE
Update nexus3 version to 3.13.0-01

### PR DESCRIPTION
**Pull request by wurbanski**
Update nexus3 spec to use 3.13.0-01

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Test this, please.

**Comment by juliogonzalez** [comment]
Change looks good. Waiting for the tests before merging and releasing.

**Comment by juliogonzalez** [comment]
Ah, yes, it's failing because the main script was not changed.

@wurbanski can you change `nexus-oss-rpm` script, line 58 from:
```
  3) VERSION="3.12.1-01"
```
to
```
  3) VERSION="3.13.0-01"
``` 
?

Thanks!

And now that I see this, I think I will modify `nexus-oss-rpm` to extract the URL from Source0 at the spec, but that will be after releaseing 3.13.0-01.

**Comment by wurbanski** [comment]
@juliogonzalez Hi, I've fixed this as well. :)

**Comment by juliogonzalez** [comment]
Tested and merging.

Thanks @wurbanski!

**Pull request merged**
