### PR TITLE
Update version, add Requires java, fix user

### PR DESCRIPTION
**Pull request by patsevanton**
Hello.
Send Pull requist "Update version, add Requires java, fix user"
I changed run_as_user to %{name}
This spec can build:
https://copr.fedorainfracloud.org/coprs/antonpatsev/nexus-oss-rpms/package/nexus/

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Hi @patsevanton,

Thank you for the PR, specially because only with it I noticed that Sonatype changed the place where they publish the release notes (so I missed 3.5.1, 3.5.2, 3.6.0, 3.6.1 and 3.6.2.

As I always prefer to track all versions at the repo, I will make the changes but will give you the credit at the change file (you did not modify it!) when I proceed to the 3.6.1 release (and then will close the release).

Other than that, I need to check the java dependency. It is not present right now because there as a problem (at least for RHEL/CentOS6), where there wasn't a metapackage 'java' that allows java software to run with whatever JVM is installed (if I added your change that means that it will run only with openJDK8, but not with Oracle JVM 8 or with any openJDK/Oracle versions (9 should work with nexus 3 as well).

Also I am not sure about changing the package name from nexus3 to nexus, but if we do it, this means we to modify the spec so nexus (now 3.x) and nexus3 are not installed at the same time (something that was possible since nexus was 2.x and nexus3 was 3.x).

**Comment by juliogonzalez** [comment]
@patsevanton can you review #7?

It is basically this PR with just three differences:

1. Don't require OpenJDK, since it is possible the users want to use Oracle JDK for any reason.
2. However we require java >= 1.8.0 (since java is a virtual package requiring java = 1.8.0 does not work, but by default at CentOS 6/7 and Amazon Linux this installs OpenJDK8), and we check that java 8 is the default JVM for the system, in case both JDK8 and JDK9 are installed and JDK9 is the default one.
3. Don't change package name from nexus to nexus3, since nexus is for Nexus 2.x which is still not end of life. But #3 is created to track it and make the change as soon as Nexus 2.x is deprecated.

**Comment by juliogonzalez** [comment]
Ping @patsevanton

**Comment by patsevanton** [comment]
Hi!
I have got a cold (fell ill)
Will answer later

**Comment by patsevanton** [comment]
Hi!
I see new commit :)
I think need close PR, download new code from master and try build rpm.
Thank you

**Pull request closed without merging**
