### PR TITLE
Added remove /etc/rc.d/init.d/%{name} and added systemd support

### PR DESCRIPTION
**Pull request by patsevanton**
/etc/rc.d/init.d/nexus3 stay after remove package nexus3 

systemctl status nexus3.service 
Warning: nexus3.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● nexus3.service - LSB: nexus
   Loaded: loaded (/etc/rc.d/init.d/nexus3; generated; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

### CODE REVIEW

**Comment by juliogonzalez** [comment]
test this please (asking Jenkins to test how this works for the different distributions).

**Comment by juliogonzalez** [comment]
Ok, it seems to to me that the test could are failing because of the PR conflicts with master. Let's retry after such conflicts are fixed at the ```systemd``` branch.

**Comment by patsevanton** [comment]
Hello!
May be close this big PR and divide to small PR ?

**Comment by juliogonzalez** [comment]
@patsevanton, I am just fixing some problems with package removal since:
```bash
%postun
rm -f $RPM_BUILD_ROOT/etc/rc.d/init.d/%{name}
```
was not required.

At the same time I am porting your previous changes for Nexus 2, and adding SUSE/openSUSE support (this will use your ```use_systemd``` macro since daemon-reload is required).

Once I have the changes ready, and ported to systemd branch, I will ping you so you can work there adding full systemd support.

Let's keep this PR opened meanwhile.

**Comment by patsevanton** [comment]
Ok. i will check next changes. :)

**Comment by juliogonzalez** [comment]
@patsevanton all changes on my side are complete and availabe at master and ```systemd``` branches.

You will notice at the SPEC files that now we are already using systemd for the systems that replaced sysvinit.

Now the remaining thing is adding the service file and adapt the SPEC files to use it instead of /etc/init.d/<nexus|nexus3>

You have two options for the new PR:

- Ideally you should update the ```Release``` tag and update the changelog, and extra points if you do it for nexus2 (```nexus-oss.spec```). In this case, send the PR against the branch ```master```
- Otherwise, just do the basics for Nexus 3, send the PR against the branch ```systemd```and I will take care of the rest before we merge changes to ```master```

**Comment by patsevanton** [comment]
@juliogonzalez Hello!
i checked nexus2 and 3 in systemd branch on CentOS 6 and CentOS 7- all build work.

I dont understant about "update the Release tag and update the changelog, and extra points if you do it for nexus2 (nexus-oss.spec)." I see tag (release) 2.14.5.02-1. What is update the changelog?

**Comment by juliogonzalez** [comment]
Hi @patsevanton:

Despite systemd works fine now with systemd, I guess you wanted to use a native systemd service, instead of using sysv compatibility.

If that's the case, you need to change ```Release:``` tag at the SPEC files, and the add a new entry at section ```%changelog```.

For example, after you change nexus3.spec you need to change:

```Release: 1%{?dist}```
to
```Release: 2%{?dist}```

And at %changelog, add a new entry:

```
* Thu Dec 30 2017 Anton Patsev <apatsev@luxoft.com> - 3.6.2.01-2
- Stop requiring sysvinit compatibility for systemd
- Add systemd service
```

If all you wanted is having systemd working and you don't care about using sysv-compatibility, let me know and I will complete the work to use a native systemd service :-)

**Pull request closed without merging**
